---
webClient:
  host: 127.0.0.1
  port: "8000"
credentials:
  username: admin
  password: admin
plugins:
  - type: jwt
    validations:
      - name: public
        secret: unique
        claims:
        - key: system
          value: public
      - name: private
        secret: unique
        claims:
        - key: system
          value: private
        - key: user
          value:
        - key: role
          value: 
secrets:
  - name: unique
    path: JWT_SECRET
endpoints:
  - base: /api/test
    backend:
      - pattern: /public
        method: GET
        target:
          url: http://localhost:8080/target
          ssl: false
          method: GET
          encrypted: false
        plugin:
          jwtEnabled: true
          jwtName: public
      - pattern: /private
        method: GET
        target:
          url: http://localhost:8080/target
          ssl: false
          method: GET
          encrypted: false
        plugin:
          jwtEnabled: true
          jwtName: private

